### ISSUE TITLE
Document how to add a platform

### ISSUE THREAD

**Issue by cameronmcefee** [getsentry/sentry-release-registry#4]
I came here to add the Java platforms but it wasn't obvious how I add a new platform. What is involved?

**Comment by untitaker** [comment]
https://github.com/getsentry/sentry-release-registry/commit/6c6f0b26c06b4f7c4e1a7c596f904215b28eaf9f

I hope this helps

**Comment by untitaker** [comment]
i wonder @cameronmcefee , did you ever get around to adding the java stuff? lmk if you need help

**Comment by cameronmcefee** [comment]
I did not, I've had too much to do and it's not something I can maintain myself :-/ This would be better for Brett to know about but he doesn't seem to have access to this repo (or at least I can't @ him)
